# generate_report.py
import pandas as pd
import os
from datetime import datetime

TEMPLATE = """# BeaversTank Report

## 📍 Top Selected Patches

| Rank | Patch ID | Score | Coordinates (Lon, Lat) |
|------|----------|-------|-------------------------|
{patch_table}

---

## 🌍 Composite Map + Selected Patches
![Composite Map]({composite_map_path})

## 📈 Pareto Plot (2D)
![Pareto 2D]({pareto_2d_path})

## 📊 Pareto Plot (3D - Screenshot)
![Pareto 3D]({pareto_3d_path})

---

## 🧠 AI Summary (coming soon)

This section will be generated by an LLM.
It will provide human-friendly interpretations of the optimization results, trade-offs between objectives, and insights into why certain patches were selected.

_(Placeholder for LLM-generated explanation)_

---

Generated on {date}
"""

def generate_report(results_csv, composite_img, pareto2_img, pareto3_img, output_md="report.md"):
    df = pd.read_csv(results_csv)
    rows = []
    for _, row in df.head(10).iterrows():
        rows.append(f"| {row['rank']} | {row['patch_id']} | {row['score']:.3f} | ({row['centroid_x']:.4f}, {row['centroid_y']:.4f}) |")
    patch_table = "\n".join(rows)

    report = TEMPLATE.format(
        patch_table=patch_table,
        composite_map_path=composite_img,
        pareto_2d_path=pareto2_img,
        pareto_3d_path=pareto3_img,
        date=datetime.now().strftime("%Y-%m-%d %H:%M")
    )

    with open(output_md, 'w') as f:
        f.write(report)

    print(f"✅ Report saved to {output_md}")
